### ISSUE TITLE
Mind making it work for newer Gregtech versions?

### ISSUE THREAD

**Issue by Someonerandomidk** [serenibyss/Serendustry#12]
So uhhhh i really like this mod but the problem is that you cant play it with any gregtech version that is higher than 2.6.2 because then some really weird "java.lang.NoClassDefFoundError: gregtech/api/GregTechAPI$MaterialEvent" happens, i have tried fixing it myself but i cant =(, so well uh, you would mind making this mod work with gregtech versions higher than that one?

**Comment by serenibyss** [comment]
https://github.com/serenibyss/Serendustry/releases/tag/v0.0.3
